[server]
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200
enableStaticServing = false
runOnSave = false

[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[client]
caching = false
displayEnabled = false
showErrorDetails = false

[theme]
base = "light"
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"

[logger]
level = "error"
messageFormat = "%(asctime)s.%(msecs)03d %(name)s: %(levelname)s: %(message)s"

[global]
developmentMode = false